### ISSUE TITLE
Releases to pypi

### ISSUE THREAD

**Issue by robmarkcole** [isaaccorley/torchseg#12]
I see https://pypi.org/project/torchseg/ but no releases on this repo yet. I assume the version `torchseg 0.0.1a2` on pypi is an initial test release from master?

**Comment by isaaccorley** [comment]
I am releasing pre-releases so users can still install the latest development version on pypi which has the latest features. I'll be doing a stable release soon though.

**Comment by isaaccorley** [comment]
You can install the pre-release using `pop install --pre torchseg`
