### ISSUE TITLE
Examples on using this library with QAT

### ISSUE THREAD

**Issue by steven-spec** [isaaccorley/torchseg#5]
Thank you for such an easy library to use.
My question is, do you have some examples as to how to use Quantized Aware Training with this library? Is there something specific I would need to know to be able to train with this library in QAT mode?

**Comment by isaaccorley** [comment]
Hi @steven-spec I'm currently working on adding an example notebook which uses [PyTorch Lightning](https://lightning.ai/docs/pytorch/stable/). I believe it supports QAT. See more information [here](https://lightning.ai/docs/pytorch/stable/advanced/pruning_quantization.html).

**Comment by notprime** [comment]
Hi @steven-spec , does Isaac's answer suit your need? So that we can close this issue. Btw, we'll provide lots of tutorial for torchseg in the near future 😎

**Comment by steven-spec** [comment]
> Hi @steven-spec , does Isaac's answer suit your need? So that we can close this issue. Btw, we'll provide lots of tutorial for torchseg in the near future 😎

yes, thanks, this issue can close
